name: CI

on:
  pull_request:
    branches:
      - main
      - stage

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
